#!/bin/bash
### BEGIN INIT INFO
# Provides:          mon_super_archiver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

case "$1" in
    start)
        echo "Starting mon_super_archiver"
        /bin/bash /bin/mon_super_archiver/main.sh --upload &
        ;;
    stop)
        echo "Stopping mon_super_archiver"
        pkill -f /bin/mon_super_archiver/main.sh
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0